<?php

return [
    'css_js_version' => '2.4.9',

    'maxAttempts' => 3,
    'decayMinutes' => 2,

    'api_key' => '',
    'fcm_google_api_push_key' => '',

    'api_success_res' => 200,
    'api_forcefully_logout_res' => 203,
    'api_error_res' => 202,
    
    'token_expiration_time_mins' => 30,

    'PUBLIC_PATH' => '',

     /************PERMISION OF ADMIN PENAL MODULE WISE***************/
    'admin_module_permission' => [
        'dashboard' => [
            'index' => ['super_admin','sub_admin'],
        ],
        'profile' => [
            'index' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
        ],
        'delete' => [
            'index' => ['super_admin','sub_admin'],
        ],
        'status' => [
            'index' => ['super_admin','sub_admin'],
        ],
        'admins' => [
            'index' => ['super_admin'],
            'add' => ['super_admin'],
            'insert' => ['super_admin'],
            'edit' => ['super_admin'],
            'update' => ['super_admin'],
            'information' => ['super_admin'],
        ],
        'users' => [
            'index' => ['super_admin','sub_admin'],
            'add' => ['super_admin','sub_admin'],
            'insert' => ['super_admin','sub_admin'],
            'edit' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
            'information' => ['super_admin','sub_admin'],
        ],
        'reports' => [
            'index' => ['super_admin','sub_admin'],
            'export' => ['super_admin','sub_admin'],            
        ],
        'contact-us' => [
            'index' => ['super_admin','sub_admin'],
            'add' => ['super_admin','sub_admin'],
            'insert' => ['super_admin','sub_admin'],
            'edit' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
            'information' => ['super_admin','sub_admin'],
        ],        
        'mail-settings' => [
            'index' => ['super_admin','sub_admin'],
            'add' => ['super_admin','sub_admin'],
            'insert' => ['super_admin','sub_admin'],
            'edit' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
            'information' => ['super_admin','sub_admin'],
        ],
        'web-pages' => [
            'index' => ['super_admin','sub_admin'],
            'add' => ['super_admin','sub_admin'],
            'insert' => ['super_admin','sub_admin'],
            'edit' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
            'information' => ['super_admin','sub_admin'],
        ],
        'settings' => [
            'index' => ['super_admin','sub_admin'],
            'add' => ['super_admin','sub_admin'],
            'insert' => ['super_admin','sub_admin'],
            'edit' => ['super_admin','sub_admin'],
            'update' => ['super_admin','sub_admin'],
            'information' => ['super_admin','sub_admin'],
        ],
    ],

    /************************* S3 BUCKET MEDIA PATHS **************************** */
    
    's3_admin_big' => 'admin/big/',
    's3_admin_thumb' => 'admin/thumb/',
    's3_wishlist_big' => 'wishlist/big/',
    's3_wishlist_thumb' => 'wishlist/thumb/',
    's3_wishlist_video' => 'wishlist/video/',
    's3_idea_big' => 'idea/big/',
    's3_idea_thumb' => 'idea/thumb/',
    's3_idea_video' => 'idea/video/',
    's3_education_big' => 'education/big/',
    's3_education_thumb' => 'education/thumb/',
    's3_education_video' => 'education/video/',
    's3_education_document' => 'education/document/',
    's3_career_big' => 'career/big/',
    's3_career_thumb' => 'career/thumb/',
    's3_career_video' => 'career/video/',
    's3_career_document' => 'career/document/',

    's3_diary_big' => 'diary/big/',
    's3_diary_thumb' => 'diary/thumb/',
    's3_diary_video' => 'diary/video/',
    's3_lifelesson_big' => 'lifelesson/big/',
    's3_lifelesson_thumb' => 'lifelesson/thumb/',
    's3_lifelesson_video' => 'lifelesson/video/',
    's3_dream_big' => 'dream/big/',
    's3_dream_thumb' => 'dream/thumb/',
    's3_dream_video' => 'dream/video/',
    's3_experience_big' => 'experience/big/',
    's3_experience_thumb' => 'experience/thumb/',
    's3_experience_video' => 'experience/video/',
    's3_first_big' => 'first/big/',
    's3_first_thumb' => 'first/thumb/',
    's3_first_video' => 'first/video/',
    's3_last_big' => 'last/big/',
    's3_last_thumb' => 'last/thumb/',
    's3_last_video' => 'last/video/',
    's3_spiritual_journey_big' => 'spiritual-journey/big/',
    's3_spiritual_journey_thumb' => 'spiritual-journey/thumb/',
    's3_spiritual_journey_video' => 'spiritual-journey/video/',
    's3_feed_document' => 'feed-document/[id]/',
    's3_user_big' => 'user/big/',
    's3_user_thumb' => 'user/thumb/',
    's3_moment_big' => 'moment/big/',
    's3_moment_thumb' => 'moment/thumb/',
    's3_moment_video' => 'moment/video/',
    's3_asset_document' => 'asset/document/',
    's3_liability_document' => 'liability/document/',
    's3_family_tree' => 'familytree/',
    's3_milestone_big' => 'milestone/big/',
    's3_milestone_thumb' => 'milestone/thumb/',
    's3_milestone_video' => 'milestone/video/',
    's3_banner_big' => 'banner/big/',
    's3_banner_thumb' => 'banner/thumb/',

    /************************* TYPE FOR TABLES ******************************/

    'tableType' => array(
        '1' => 'user_feeds',
        '2' => 'user_wish_lists',
        '3' => 'user_wish_list_likes',
        '4' => 'user_wish_list_comments',
        '5' => 'user_ideas',
        '7' => 'user_idea_likes',
        '8' => 'user_idea_comments',
        '9' => 'user_diaries',
        '10' => 'user_diary_likes',
        '11' => 'user_diary_comments',
        '12' => 'user_life_lessons',
        '13' => 'user_life_lesson_likes',
        '14' => 'user_life_lesson_comments',
        '15' => 'user_dreams',
        '16' => 'user_dream_likes',
        '17' => 'user_dream_comments',
        '18' => 'user_education',
        '19' => 'user_career',
        '20' => 'user_experiences',
        '21' => 'user_experience_likes',
        '22' => 'user_experience_comments',
        '23' => 'user_first_lasts',
        '24' => 'user_first_last_likes',
        '25' => 'user_first_last_comments',
        '26' => 'user_spiritual_journeys',
        '27' => 'user_spiritual_journey_likes',
        '28' => 'user_spiritual_journey_comments',
        '29' => 'user_moments',
        '30' => 'user_moment_files',
        '31' => 'user_moment_likes',
        '32' => 'user_moment_comments',
        '33' => 'user_assets',
        '34' => 'user_liabilities',

        '35' => 'user_education_likes',
        '36' => 'user_education_comments',
        '37' => 'user_career_likes',
        '38' => 'user_career_comments',  
        '39' => 'user_family_tree',

        '40' => 'user_milestones',
        '41' => 'user_milestone_likes',
        '42' => 'user_milestone_comments',
        
    ),
    'user_feed_type' => array(
        'wish_list' => 2,
        'idea' => 5,
        'diary' => 9,
        'life_lessons' => 12,
        'dreams' => 15,
        'education' => 18,
        'career' => 19,
        'experiences' => 20,
        'first_lasts' => 23,
        'spiritual_journeys' => 26,
        'moments' => 29,
        'milestones' => 40,
    ),
    'user_feed_type_name' => array(
        2  => 'Wish List',
        5 => 'Idea' ,
        9 => 'Diary',
        12=> 'Life Lesson' ,
        15 => 'Dream' ,
        18  => 'Education' ,
        19 => 'Career' ,
        20 => 'Experience' ,
        23 => 'FirstLast' ,
        26 => 'Spiritual Journey',
        29 => 'Special Moments' ,
        40 => 'Milestones',

       
    ),
    'networth__nominee_login_allowed_time'=> 5,

    'user_relation_type' => array(
        'Self' => 1,
        'Mother' => 2,
        'Father' => 3,
        'Sibling' => 4,
        'Child' => 5,
        'Spouse' => 6,
    ),

    'fmailylist_relation_type' => array(
        1 => 'Self',
        2 => 'Mother',
        3 => 'Father',
        4 => 'Sibling' ,
        5 => 'Child' ,
        6 => 'Spouse',
    ),
];